package agent

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
)

var _ Setup = (*Claude)(nil)

func init() {
	Register(&Claude{})
}

// PluginFS is set by main.go with the embedded plugin files.
var PluginFS fs.FS

// PluginVersion is set by main.go from the embedded plugin.json.
var PluginVersion = "0.1.0"

const pluginID = "acho@acho"

// Claude registers acho as a native Claude Code plugin with allowlisted tools.
type Claude struct{}

func (c *Claude) Name() string        { return "claude" }
func (c *Claude) Description() string { return "Register acho as native Claude Code plugin" }

func (c *Claude) Setup() error {
	if _, err := exec.LookPath("claude"); err != nil {
		return fmt.Errorf("claude CLI not found in PATH — install Claude Code first")
	}

	marketplacePath, err := installMarketplace()
	if err != nil {
		return err
	}

	if err := installPlugin(marketplacePath); err != nil {
		return err
	}

	if err := writeClaudeSettings(); err != nil {
		return err
	}

	// Remove old-style MCP registration if it exists
	_ = exec.Command("claude", "mcp", "remove", "acho").Run()

	// Clean up old locations
	if home, err := os.UserHomeDir(); err == nil {
		_ = os.Remove(filepath.Join(home, ".claude", "mcp", "acho.json"))
		_ = os.RemoveAll(filepath.Join(home, ".acho", "plugin"))
	}

	return nil
}

// installMarketplace writes a local Claude marketplace containing the embedded plugin.
func installMarketplace() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("failed to resolve home dir: %w", err)
	}

	marketplaceRoot := filepath.Join(home, ".claude", "plugins", "marketplaces", "acho")
	pluginRoot := filepath.Join(marketplaceRoot, "plugin")

	if err := extractPlugin(pluginRoot); err != nil {
		return "", err
	}

	manifestPath := filepath.Join(marketplaceRoot, ".claude-plugin", "marketplace.json")
	if err := os.MkdirAll(filepath.Dir(manifestPath), 0755); err != nil {
		return "", fmt.Errorf("failed to create marketplace dir: %w", err)
	}

	marketplace := map[string]any{
		"$schema":     "https://anthropic.com/claude-code/marketplace.schema.json",
		"name":        "acho",
		"description": "Local marketplace generated by acho agent-setup",
		"owner": map[string]any{
			"name": "PuntoPost",
		},
		"plugins": []any{
			map[string]any{
				"name":        "acho",
				"description": "Acho memory persistence",
				"version":     PluginVersion,
				"author": map[string]any{
					"name": "JGRC",
				},
				"source": "./plugin",
			},
		},
	}

	data, err := json.MarshalIndent(marketplace, "", "  ")
	if err != nil {
		return "", fmt.Errorf("failed to encode marketplace manifest: %w", err)
	}
	if err := os.WriteFile(manifestPath, append(data, '\n'), 0644); err != nil {
		return "", fmt.Errorf("failed to write marketplace manifest: %w", err)
	}

	return marketplaceRoot, nil
}

// extractPlugin copies embedded plugin files to the destination directory.
func extractPlugin(destRoot string) error {
	if PluginFS == nil {
		return fmt.Errorf("plugin files not embedded — this is a build error")
	}

	if err := os.RemoveAll(destRoot); err != nil {
		return fmt.Errorf("failed to clean plugin dir: %w", err)
	}

	walkErr := fs.WalkDir(PluginFS, ".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		dest := filepath.Join(destRoot, path)

		if d.IsDir() {
			return os.MkdirAll(dest, 0755)
		}

		data, err := fs.ReadFile(PluginFS, path)
		if err != nil {
			return fmt.Errorf("read embedded %s: %w", path, err)
		}

		if err := os.WriteFile(dest, data, 0644); err != nil {
			return fmt.Errorf("write %s: %w", dest, err)
		}

		// Make .sh files executable
		if filepath.Ext(path) == ".sh" {
			if err := os.Chmod(dest, 0755); err != nil {
				return fmt.Errorf("chmod %s: %w", dest, err)
			}
		}

		return nil
	})
	if walkErr != nil {
		return fmt.Errorf("failed to extract plugin: %w", walkErr)
	}

	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to resolve home dir: %w", err)
	}

	dataDir := filepath.Join(home, ".claude", "plugins", "data", "acho-acho")
	if err := os.MkdirAll(dataDir, 0755); err != nil {
		return fmt.Errorf("failed to create plugin data dir: %w", err)
	}

	return nil
}

func installPlugin(marketplacePath string) error {
	addCmd := exec.Command("claude", "plugin", "marketplace", "add", marketplacePath)
	if output, err := addCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to add local marketplace: %w: %s", err, output)
	}

	installCmd := exec.Command("claude", "plugin", "install", pluginID, "--scope", "user")
	if output, err := installCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to install Claude plugin: %w: %s", err, output)
	}

	return nil
}

var achoMCPTools = []string{
	"mcp__plugin_acho_acho__context",
	"mcp__plugin_acho_acho__save",
	"mcp__plugin_acho_acho__search",
	"mcp__plugin_acho_acho__get",
	"mcp__plugin_acho_acho__list",
	"mcp__plugin_acho_acho__update",
	"mcp__plugin_acho_acho__delete",
}

// writeClaudeSettings adds enabledPlugins and tool permissions to ~/.claude/settings.json.
func writeClaudeSettings() error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}

	settingsPath := filepath.Join(home, ".claude", "settings.json")
	settings := map[string]any{}

	if data, err := os.ReadFile(settingsPath); err == nil {
		if err := json.Unmarshal(data, &settings); err != nil {
			return fmt.Errorf("failed to parse %s: %w", settingsPath, err)
		}
	} else if !os.IsNotExist(err) {
		return err
	}

	// Enable plugin
	enabled, _ := settings["enabledPlugins"].(map[string]any)
	if enabled == nil {
		enabled = map[string]any{}
		settings["enabledPlugins"] = enabled
	}
	enabled[pluginID] = true

	// Allowlist tools
	perms, _ := settings["permissions"].(map[string]any)
	if perms == nil {
		perms = map[string]any{}
		settings["permissions"] = perms
	}

	var allow []any
	if existing, ok := perms["allow"].([]any); ok {
		allow = existing
	}

	existingSet := map[string]bool{}
	for _, entry := range allow {
		if s, ok := entry.(string); ok {
			existingSet[s] = true
		}
	}

	for _, tool := range achoMCPTools {
		if !existingSet[tool] {
			allow = append(allow, tool)
		}
	}

	perms["allow"] = allow

	data, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(settingsPath, append(data, '\n'), 0644)
}
